sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start creating an image with dockerfile"
  - docker build -t ehgns5668/docker-react-app Dockerfile.dev ./

script:
  - docker run -e CI=true ehgns5668/docker-react-app npm run test -- --coverage

after_success: 
  - echo "Test Success"